source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'protected_attributes'
gem 'high_voltage'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'cucumber-rails'
  gem 'launchy'
  gem 'capybara'
end

gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
    :github => 'anjlab/bootstrap-rails'
gem 'devise'
gem 'cancan'
gem 'rolify', '~> 3.3.0.rc4'
gem 'simple_form'
gem 'quiet_assets'
gem 'figaro'
gem 'better_errors'
gem 'binding_of_caller'
