source 'https://rubygems.org'

gem 'rails'

# Rails defaults
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

# Tutorial Gems
gem 'activerecord-tableless'
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
   :github => 'anjlab/bootstrap-rails'
gem 'figaro'
gem 'google_drive'
gem 'high_voltage'
gem 'simple_form'


group :development do
  gem 'sqlite3'
  gem 'better_errors'
  gem 'quiet_assets'
end

group :production do
  gem 'pg'
  gem 'thin'
  gem 'rails_on_heroku'
end
